---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy12
  namespace: one
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/mygame
          ports:
            - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: one
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
